## Numpy Basics

Bienvenido a la librería Numpy. Esta librería es una de las herramientas más populares y versátiles para el cálculo numérico en Python. Ofrece una amplia variedad de funciones y herramientas para trabajar con matrices, vectores y estructuras de datos multidimensionales. Con Numpy, puedes realizar operaciones matemáticas complejas de forma rápida y sencilla, lo que la hace ideal para aplicaciones científicas, financieras y estadísticas. Esta librería también es útil para la creación de gráficos y visualizaciones avanzadas. Si estás interesado en aprender a usar Numpy para tu proyecto, ¡estás en el lugar correcto!

In [24]:
# La convención para el uso de NumPy
import numpy as np

In [25]:
# Creando un arreglo, a partir de una lista de python
lista_python = [0,1,2,3]

mi_array = np.array( [0,1.0,2,3,5] , dtype='float' )
mi_array.dtype

dtype('float64')

In [26]:
mi_array = np.arange(0,10)
mi_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# Usando metodos de creacion de arreglos multidimensionales
# ones, zeros, identity, eye
mi_array = np.ones( (3,3) )
mi_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

El resto de los metodos para crear arreglos que ofrece numpy:<br>
http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html<br>

----

In [28]:
# Que hay dentro del objeto mi_arreglo
print ('Numero de elementos ' , mi_array.size)
print ('Forma dimensiones ' , mi_array.shape)
print ('Numero dimensiones ' , mi_array.ndim)
print ('Tipo de dato ' , mi_array.dtype)

#dir(mi_array)

Numero de elementos  9
Forma dimensiones  (3, 3)
Numero dimensiones  2
Tipo de dato  float64


### Visualizando la informacion
- Ultimo eje (dimension) se visualiza de izquierda a derecha
- Penultimo eje se visualiza de arriba a abajo.
- El resto tambien se muestran de arriba a abajo, donde cada bloque es separado del siguiente por una linea vacia.

In [29]:
# arreglo 2D
a = np.arange(12)

a.resize(4,3)
print (a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
# arrreglo 3D
c = np.arange(24).reshape(2,3,4)
print (c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Las operaciones basicas
Todas las operaciones aritmeticas sobre los arreglos de numpy se hacen elemento a elemento. Se genera un nuevo arreglo y se llena con el resultado

In [31]:
a = np.arange(4).reshape(2,2)
b = np.ones((2,2))
b = b + 1
c = a * b


print (a)
print (b)
print ('-')
print (c)


[[0 1]
 [2 3]]
[[2. 2.]
 [2. 2.]]
-
[[0. 2.]
 [4. 6.]]


In [32]:
# El producto de matrices
c = np.dot(a,b)
print (c)

[[ 2.  2.]
 [10. 10.]]


### "Broadcasting"
Describe el como se comportan los arreglos de numpy de diferenctes dimensiones durante las operaciones aritmeticas.

![alt text](images/np_broadcasting.png "Ejemplos broadcasting")

In [33]:
# "Broadcasting" Operaciones sobre arreglos que no tienen la misma dimension, se repiten en los siguientes bloques
# Regla del broadcasting dice que dos dimensiones son compatibles cuando:
# - Son iguales en las primeras dimensiones
# - Una de ellas es uno.

a = np.arange(12).reshape(4,3)
b = np.ones((3))

print (a, '-', b)
print ('=')
print (a - b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] - [1. 1. 1.]
=
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [34]:
# Otro ejemplo de "broadcasting"
x = np.arange(4)
xx = x.reshape(4,1)


print ('x:', x.shape)
print ('xx:', xx.shape)
print (xx * x)

x: (4,)
xx: (4, 1)
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [35]:
y = np.ones((3,3))


print ("y shape : " , y.shape)
print ("x shape : " , x.shape)
print ("y : " , y)
print ("x : " , x )


y shape :  (3, 3)
x shape :  (4,)
y :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
x :  [0 1 2 3]


In [36]:
x + y # Generara un error pues las dimensiones no corresponden.

ValueError: operands could not be broadcast together with shapes (4,) (3,3) 

In [37]:
y = np.ones((4,4))

In [38]:
print (xx)
print (y)
xx + y

[[0]
 [1]
 [2]
 [3]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

### Metodos ya incluidos en la clase ndarray
Muchos metodos ya se encuentran integrados en la clase *ndarray* de NumPy

In [39]:
a = np.random.random((2,3))
a

array([[0.53762659, 0.51880924, 0.42818816],
       [0.89522233, 0.76837327, 0.6129353 ]])

In [40]:
a.sum()

3.761154886561607

In [41]:
a.min(axis=1)

array([0.42818816, 0.6129353 ])

In [42]:
a.max()

0.8952223296064991

Por default estas operaciones se hacen sobre todos los elementos del arreglo, salvo que se especifiquen, que solo se desea hacer la operacion sobre algun eje en especifico.

![Alt Text](images/axis.png "Numpy axis order")

In [43]:
# La suma de cada columna
a.sum(axis=0)

array([1.43284892, 1.28718251, 1.04112345])

In [44]:
# La suma de cada renglon
a.sum(axis=1)

array([1.48462399, 2.2765309 ])

In [45]:
# La suma aculumativa sobre cada renglon
b = np.arange(12).reshape(3,4)
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

### Funciones universales
Funciones matematicas que se realizan de elemento a elemento

Listado: http://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations


In [46]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [47]:
np.sin(b)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [48]:
c = np.array([2,2,2,2])
np.add(b,c)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

### Seleccion de rangos, indexado e iteraciones
- Arreglos 1D se pueden acceder por indices, recortar e iterar sobre sus elementos, como una lista de python.
- Arreglos 2D, tienen un indice por eje, y estos indices se dan por un tipo de dato **tuple**
- Arreglos multidimensionales tienen un indice por cada eje, de igual forma estan dados por un **tuple**

In [49]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [50]:
# Buscar dentro del arreglo, y retornar indices
np.where(a > 10)

(array([4, 5, 6, 7, 8, 9], dtype=int64),)

In [51]:
print (a[2])

print (a[2:5])
print (a[0:-1:2])             # Usando un paso de dos indices
print (a[np.array([2,4,6])])  # Elementos con indice 2 , 4 y 6


4
[ 4  9 16]
[ 0  4 16 36 64]
[ 4 16 36]


In [52]:
# Usando los mismos arreglos ndarray para referirnos a indices de otro arreglo.
indices = np.array([5,8,1])
a[indices]

array([25, 64,  1])

In [53]:
#
# Visualizando la seleccion de rangos

arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

![Alt Text](images/slicing1.png "Rangos")

In [54]:
arr[0:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
arr[2,1:]

array([11, 12, 13, 14])

In [56]:
# Modificando datos sobre una region del arreglo.
a[4:6] = -999
a

array([   0,    1,    4,    9, -999, -999,   36,   49,   64,   81])

In [57]:
# Iterar sobre sus elementos.
for el in a:
    print (el, ',')

0 ,
1 ,
4 ,
9 ,
-999 ,
-999 ,
36 ,
49 ,
64 ,
81 ,


### Aunque alerta, para que quisieramos iterar sobre sus elementos si tenemos funciones universales y podemos vectorizar la mayoria de las operaciones..

In [58]:
# Arreglos multidimensionales

# Equivalente a
# def func(x,y):
#   return 10 * x+y
func = lambda x,y : 10*x+y         # palabra reservada lambda produce una funcion inline

b = np.fromfunction(func,(5,4))
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [59]:
# Segundo renglon
b[1,:]

array([10., 11., 12., 13.])

In [60]:
# Ultima columna
b[:,-1]

array([ 3., 13., 23., 33., 43.])

In [61]:
# Iterando sobre arreglos multidimensionales.
for renglon in b:
    print (renglon , ',')

[0. 1. 2. 3.] ,
[10. 11. 12. 13.] ,
[20. 21. 22. 23.] ,
[30. 31. 32. 33.] ,
[40. 41. 42. 43.] ,


In [62]:
# El atributo flat entrega el iterable de todos los elementos del arreglo
for el in b.flat:
    print (el, ',', end="")

0.0 ,1.0 ,2.0 ,3.0 ,10.0 ,11.0 ,12.0 ,13.0 ,20.0 ,21.0 ,22.0 ,23.0 ,30.0 ,31.0 ,32.0 ,33.0 ,40.0 ,41.0 ,42.0 ,43.0 ,

### Ordenando, buscando y contando el arreglo.
Metodos para la busqueda y ordenado de datos en arreglos de numpy<br>
http://docs.scipy.org/doc/numpy/reference/routines.sort.html

In [63]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
# Elementos del arreglo, con alguna condicion
a[(a>2) & (a<9)]

array([3, 4, 5, 6, 7, 8])

In [65]:
# Los elementos que cumplan con alguna condición
(a > 4) & (a<10)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [66]:
# Numpy where(cond, x, y), si se cumple la condicion, recupera de "x", de otra forma, de "y"
np.where(a >5 , a , 999)

array([[999, 999, 999],
       [999, 999, 999],
       [  6,   7,   8],
       [  9,  10,  11]])

In [67]:
# Indices de elementos que cumplan la siguiente condicion
np.argwhere((a>2) & (a<9))

array([[1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)

In [68]:
# Indices con minimo y maximo
print (np.argmin(a))
print (np.argmax(a))

0
11


### Manipulando la forma de un arreglo

In [69]:
a = np.floor( np.random.random((3,4)) * 10 )
a

array([[5., 2., 8., 3.],
       [3., 7., 1., 8.],
       [2., 4., 0., 4.]])

In [70]:
a.shape

(3, 4)

In [71]:
# Aplanamos el arreglo, (Regresa referencias al arreglo original!)
a.ravel()

array([5., 2., 8., 3., 3., 7., 1., 8., 2., 4., 0., 4.])

In [72]:
# arreglo a transpuesto
a.transpose() # O tambien a.T

array([[5., 3., 2.],
       [2., 7., 4.],
       [8., 1., 0.],
       [3., 8., 4.]])

In [73]:
# Modificamos la forma del arreglo con resize
a.resize(6,2)
a

array([[5., 2.],
       [8., 3.],
       [3., 7.],
       [1., 8.],
       [2., 4.],
       [0., 4.]])

In [74]:
# reshape entrega un nuevo arreglo
# Al incluir -1 en los parametros, dejamos que numpy calcule el tamaño adecuado
a.reshape(-1,6)

array([[5., 2., 8., 3., 3., 7.],
       [1., 8., 2., 4., 0., 4.]])

### Concatenando arreglos

In [75]:
a = np.floor( 10 * np.random.random((2,2)) )
b = np.floor( 10 * np.random.random((2,2)) )

In [76]:
a

array([[4., 2.],
       [6., 8.]])

In [77]:
b

array([[6., 1.],
       [2., 0.]])

In [78]:
# Apilando los arreglos verticalemente
np.vstack( (a,b) )

array([[4., 2.],
       [6., 8.],
       [6., 1.],
       [2., 0.]])

In [79]:
# Apilando horizontalmente
np.hstack((a,b))

array([[4., 2., 6., 1.],
       [6., 8., 2., 0.]])

In [80]:
# Un arreglo de 1D
c = np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [81]:
# Al agregar np.newaxis, creamos un arreglo 2D con los datos ordenados en la columna
d = c[ :, np.newaxis]
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [82]:
np.vstack((d,d))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [83]:
np.hstack((d,d,d))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

### Copia de datos y vistas
Operando arreglos multidimensionales, en ocasiones los datos se copian a un nuevo arreglo y en otras no, para evitar confusiones veremos los casos.

In [84]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
# El operador = no hace copia de los datos, solo pasa la referencia al
# puntero donde esta la informacion
b = a
b is a

True

In [86]:
# Los cambios realizados en b, tambien afectan al arreglo a, esto sucede igual
# al pasar parametros en una funcion
b.resize(3,4)
a.shape

(3, 4)

#### Vistas o copia ligera
La diferencia con las vistas, es que dos objetos ndarray que observan a los mismos datos. <br>
Al hacer un recorte de un arreglo, estamos creado una vista.

In [87]:
c = a.view()
c is a

False

In [88]:
# Cambiamos la forma de los datos en c, sin que se afecte en a
c.resize((12))
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
# Pero al cambiar un dato en el arreglo a ...
a[0] = -9999
c

array([-9999, -9999, -9999, -9999,     4,     5,     6,     7,     8,
           9,    10,    11])

#### Copia real de datos
El metodo copy() hace una copia completa del arreglo y de sus datos.

In [91]:
d = a.copy()
d is a

False

In [92]:
d[0,0] = 5555
a

array([[-9999, -9999, -9999, -9999],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11]])

In [93]:
d

array([[ 5555, -9999, -9999, -9999],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11]])

### Arreglos con mascara
Para manejar arreglos de datos que puedan contener datos invalidos, por lo que es conveniente usar un arreglo con mascara para no incluir esos datos en las operaciones.<br>
Documentacion completa: http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

In [94]:
# Importar el modulo para arreglos con mascara
import numpy.ma as ma

In [95]:
x = np.array([1,2,-1,4,5,6,-1,8,9])
mx = ma.masked_array(x , mask=[0,0,1,0,0,0,1,0,0])
mx

masked_array(data=[1, 2, --, 4, 5, 6, --, 8, 9],
             mask=[False, False,  True, False, False, False,  True, False,
                   False],
       fill_value=999999)

In [96]:
# En todas las operaciones sobre el arreglo no se contaran los datos enmascarados.
mx.mean()

5.0

In [97]:
# Es posible crear una mascara con alguna condicion sobre el arreglo.
nmx = ma.masked_array(x , mask=(x <0))
nmx

masked_array(data=[1, 2, --, 4, 5, 6, --, 8, 9],
             mask=[False, False,  True, False, False, False,  True, False,
                   False],
       fill_value=999999)

In [98]:
# Accediendo a la mascara
mx.mask

array([False, False,  True, False, False, False,  True, False, False])

In [99]:
# Recuperar los datos validos
mx.compressed()

array([1, 2, 4, 5, 6, 8, 9])