In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49

In [2]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Invertir el vector

In [3]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [4]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [5]:
a = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
np.argwhere( a!=0 )

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 6],
       [10],
       [11],
       [12],
       [13],
       [14]], dtype=int64)

### Crear una matriz identidad de 6x6

In [6]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Crear una matriz con valores al azar con forma 3x3x3 

In [7]:
r = np.random.random((3,3,3))
r

array([[[0.9126206 , 0.69186311, 0.95616328],
        [0.0425055 , 0.45101047, 0.50683263],
        [0.97534016, 0.54107623, 0.22533146]],

       [[0.87632594, 0.45261893, 0.90154202],
        [0.80758092, 0.22173025, 0.29014111],
        [0.51340113, 0.08280711, 0.46003871]],

       [[0.40908283, 0.22861644, 0.90845419],
        [0.49082443, 0.58780078, 0.33029965],
        [0.55434647, 0.66524804, 0.68268561]]])

### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [8]:
print( r.argmax() )
print( r.ravel()[r.argmax()] )

print(r)
print(np.unravel_index(r.argmax(), r.shape))
r[np.unravel_index(r.argmax(), r.shape)]

6
0.9753401640723413
[[[0.9126206  0.69186311 0.95616328]
  [0.0425055  0.45101047 0.50683263]
  [0.97534016 0.54107623 0.22533146]]

 [[0.87632594 0.45261893 0.90154202]
  [0.80758092 0.22173025 0.29014111]
  [0.51340113 0.08280711 0.46003871]]

 [[0.40908283 0.22861644 0.90845419]
  [0.49082443 0.58780078 0.33029965]
  [0.55434647 0.66524804 0.68268561]]]
(0, 2, 0)


0.9753401640723413

### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [9]:
z = np.ones((10,10))

z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [10]:
np.tile( np.arange(0,5) , 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Crear dos arreglos al azar A y B, verificar si son iguales

In [11]:
a = np.random.random((3,3))
b = np.random.random((3,3))

a == b 

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [12]:
np.allclose(a,b)  # Con tolerancia, dada por argumentos: rtol atol



False

In [13]:
np.array_equal(a,b)

False